name: build-dataql
on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
    tags: [ '*' ]
jobs:
  build-application:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.24']
        os: [ubuntu-latest]
    steps:
      - name: install-golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout-code
        uses: actions/checkout@v4
      - name: build-application
        run: go build -o ./build/${{ matrix.os }}/dataql -v ./
